treinamento = [
    ("Olá, tudo bem?", {"cats": {"saudacao": 1, "horario": 0, "ajuda": 0, "nome": 0}}),
    ("Oi, como você está?", {"cats": {"saudacao": 1, "horario": 0, "ajuda": 0, "nome": 0}}),
    ("E aí, beleza?", {"cats": {"saudacao": 1, "horario": 0, "ajuda": 0, "nome": 0}}),
    ("Como você está?", {"cats": {"saudacao": 1, "horario": 0, "ajuda": 0, "nome": 0}}),
    ("Que horas são?", {"cats": {"saudacao": 0, "horario": 1, "ajuda": 0, "nome": 0}}),
    ("Me diga as horas.", {"cats": {"saudacao": 0, "horario": 1, "ajuda": 0, "nome": 0}}),
    ("Você pode me ajudar?", {"cats": {"saudacao": 0, "horario": 0, "ajuda": 1, "nome": 0}}),
    ("Qual o seu nome?", {"cats": {"saudacao": 0, "horario": 0, "ajuda": 0, "nome": 1}}),
    ("Quem é você?", {"cats": {"saudacao": 0, "horario": 0, "ajuda": 0, "nome": 1}}),
    ("Quantas horas tem um dia?", {"cats": {"saudacao": 0, "horario": 0, "ajuda": 1, "nome": 0}}),
    ("Oi, tudo certo?", {"cats": {"saudacao": 1, "horario": 0, "ajuda": 0, "nome": 0}}),
    ("Como vai?", {"cats": {"saudacao": 1, "horario": 0, "ajuda": 0, "nome": 0}}),
    ("Bom dia!", {"cats": {"saudacao": 1, "horario": 0, "ajuda": 0, "nome": 0}}),
    ("Boa tarde!", {"cats": {"saudacao": 1, "horario": 0, "ajuda": 0, "nome": 0}}),
    ("Boa noite!", {"cats": {"saudacao": 1, "horario": 0, "ajuda": 0, "nome": 0}}),
    ("Como você tem passado?", {"cats": {"saudacao": 1, "horario": 0, "ajuda": 0, "nome": 0}}),
    ("Como estão as coisas?", {"cats": {"saudacao": 1, "horario": 0, "ajuda": 0, "nome": 0}}),
    ("E aí, tudo certo?", {"cats": {"saudacao": 1, "horario": 0, "ajuda": 0, "nome": 0}}),
    ("Qual é a hora agora?", {"cats": {"saudacao": 0, "horario": 1, "ajuda": 0, "nome": 0}}),
    ("Pode me dizer as horas?", {"cats": {"saudacao": 0, "horario": 1, "ajuda": 1, "nome": 0}}),
    ("Qual a capital do Brasil?" , {"cats": {"saudacao": 0, "horario": 0, "ajuda": 1, "nome": 0}}),
    ("Me fale sobre as horas.", {"cats": {"saudacao": 0, "horario": 1, "ajuda": 0, "nome": 0}}),
    ("Quero saber que horas são.", {"cats": {"saudacao": 0, "horario": 1, "ajuda": 0, "nome": 0}}),
    ("Você sabe que horas são?", {"cats": {"saudacao": 0, "horario": 1, "ajuda": 0, "nome": 0}}),
    ("Qual é o horário?", {"cats": {"saudacao": 0, "horario": 1, "ajuda": 0, "nome": 0}}),
    ("Me ajuda com algo?", {"cats": {"saudacao": 0, "horario": 0, "ajuda": 1, "nome": 0}}),
    ("Você pode me ajudar com uma dúvida?", {"cats": {"saudacao": 0, "horario": 0, "ajuda": 1, "nome": 0}}),
    ("Preciso de ajuda, você pode me ajudar?", {"cats": {"saudacao": 0, "horario": 0, "ajuda": 1, "nome": 0}}),
    ("Como posso resolver isso?", {"cats": {"saudacao": 0, "horario": 0, "ajuda": 1, "nome": 0}}),
    ("Qual é seu nome mesmo?", {"cats": {"saudacao": 0, "horario": 0, "ajuda": 0, "nome": 1}}),
    ("Qual o seu nome?", {"cats": {"saudacao": 0, "horario": 0, "ajuda": 0, "nome": 1}}),
    ("Me fale seu nome.", {"cats": {"saudacao": 0, "horario": 0, "ajuda": 0, "nome": 1}}),
    ("Você é uma IA, certo?", {"cats": {"saudacao": 0, "horario": 0, "ajuda": 0, "nome": 1}}),
    ("Quem é você na verdade?", {"cats": {"saudacao": 0, "horario": 0, "ajuda": 0, "nome": 1}}),
    ("Que horas são em São Paulo?", {"cats": {"saudacao": 0, "horario": 1, "ajuda": 0, "nome": 0}}),
    ("Você sabe as horas em Brasília?", {"cats": {"saudacao": 0, "horario": 1, "ajuda": 0, "nome": 0}}),
    ("Pode me ajudar a entender isso?", {"cats": {"saudacao": 0, "horario": 0, "ajuda": 1, "nome": 0}}),
    ("Como você se chama?", {"cats": {"saudacao": 0, "horario": 0, "ajuda": 0, "nome": 1}}),
    ("Você pode me ajudar com isso?", {"cats": {"saudacao": 0, "horario": 0, "ajuda": 1, "nome": 0}}),
    ("O que você faz?", {"cats": {"saudacao": 0, "horario": 0, "ajuda": 1, "nome": 0}}),
    ("Quantas horas são agora?", {"cats": {"saudacao": 0, "horario": 1, "ajuda": 0, "nome": 0}}),
    ("Quando você pode me ajudar?", {"cats": {"saudacao": 0, "horario": 0, "ajuda": 1, "nome": 0}}),
    ("Quantas horas você tem?", {"cats": {"saudacao": 0, "horario": 1, "ajuda": 0, "nome": 0}}),
    ("Me ajude a encontrar informações.", {"cats": {"saudacao": 0, "horario": 0, "ajuda": 1, "nome": 0}}),
    ("Quantas horas faltam para o almoço?", {"cats": {"saudacao": 0, "horario": 1, "ajuda": 0, "nome": 0}}),
    ("Você pode me ajudar a resolver um problema?", {"cats": {"saudacao": 0, "horario": 0, "ajuda": 1, "nome": 0}}),
    ("Quantas horas você trabalha por dia?", {"cats": {"saudacao": 0, "horario": 1, "ajuda": 0, "nome": 0}}),
    ("Posso saber mais sobre você?", {"cats": {"saudacao": 0, "horario": 0, "ajuda": 1, "nome": 1}}),
    ("Como posso contatá-lo?", {"cats": {"saudacao": 0, "horario": 0, "ajuda": 1, "nome": 0}}),
    ("Como posso saber seu nome?", {"cats": {"saudacao": 0, "horario": 0, "ajuda": 0, "nome": 1}}),
    ("Quantas horas faltam para o dia terminar?", {"cats": {"saudacao": 0, "horario": 1, "ajuda": 0, "nome": 0}}),
    ("Você sabe a hora exata?", {"cats": {"saudacao": 0, "horario": 1, "ajuda": 0, "nome": 0}}),
    ]